"""
AI sketch generation templates for Arduino Vibe IDE.
Contains prompt templates for various Arduino hardware categories.
"""

from dataclasses import dataclass, field
from typing import Optional


# ─── Hardware templates ────────────────────────────────────────────

LED_SKETCH_TEMPLATE = """
/**
 * LED Control Sketch - {description}
 * Generated by Arduino Vibe IDE
 */

#include <FastLED.h>

// LED Configuration
#define LED_PIN        {led_pin}
#define NUM_LEDS       {num_leds}
#define LED_TYPE       {led_type}
#define COLOR_ORDER    {color_order}
#define BRIGHTNESS     {brightness}

CRGB leds[NUM_LEDS];

// Runtime command parser
#define CMD_BUFFER_SIZE 64
char cmd_buffer[CMD_BUFFER_SIZE];
int cmd_idx = 0;

// LED Effects
enum Effect {{
    EFFECT_SOLID,
    EFFECT_RAINBOW,
    EFFECT_PULSE,
    EFFECT_FIRE,
    EFFECT_WAVE,
    EFFECT_RUNNING,
    EFFECT_RANDOM,
    EFFECT_CHASE,
}};

Effect current_effect = EFFECT_SOLID;
CRGB current_color = CRGB::White;
uint8_t current_brightness = {brightness};
uint32_t last_update = 0;
uint8_t speed = 10;

void setup() {{
    Serial.begin(115200);
    while (!Serial) {{ }}  // Wait for serial (USB boards)

    LED.addLeds<LED_TYPE, LED_PIN, COLOR_ORDER>(leds, NUM_LEDS);
    LED.setBrightness(current_brightness);
    fill_solid(leds, NUM_LEDS, current_color);
    LED.show();

    Serial.println("LEDS_READY");
    Serial.print("LEDS_NUM=");
    Serial.println(NUM_LEDS);
}}

void loop() {{
    parse_serial_command();
    update_effect();
    LED.show();
}}

void parse_serial_command() {{
    while (Serial.available()) {{
        char c = Serial.read();
        if (c == '\\\\n') {{
            cmd_buffer[cmd_idx] = '\\\\0';
            process_command(cmd_buffer);
            cmd_idx = 0;
        }} else if (cmd_idx < CMD_BUFFER_SIZE - 1) {{
            cmd_buffer[cmd_idx++] = c;
        }}
    }}
}}

void process_command(char* cmd) {{
    // LED control: LED <index> <R> <G> <B>
    if (strncmp(cmd, "LED", 3) == 0) {{
        int idx, r, g, b;
        if (sscanf(cmd + 4, "%d %d %d %d", &idx, &r, &g, &b) == 4) {{
            if (idx >= 0 && idx < NUM_LEDS) {{
                leds[idx].setRGB(r, g, b);
                Serial.print("LED_");
                Serial.print(idx);
                Serial.println(" OK");
            }}
        }}
        return;
    }}

    // All LEDs: ALL <R> <G> <B>
    if (strncmp(cmd, "ALL", 3) == 0) {{
        int r, g, b;
        if (sscanf(cmd + 4, "%d %d %d", &r, &g, &b) == 3) {{
            fill_solid(leds, NUM_LEDS, CRGB(r, g, b));
            Serial.println("ALL OK");
        }}
        return;
    }}

    // Brightness: BRIGHT <0-255>
    if (strncmp(cmd, "BRIGHT", 6) == 0) {{
        int b;
        if (sscanf(cmd + 7, "%d", &b) == 1) {{
            current_brightness = constrain(b, 0, 255);
            LED.setBrightness(current_brightness);
            Serial.print("BRIGHT ");
            Serial.println(current_brightness);
        }}
        return;
    }}

    // Effect: EFFECT <name>
    if (strncmp(cmd, "EFFECT", 6) == 0) {{
        char effect_name[16];
        if (sscanf(cmd + 7, "%15s", effect_name) == 1) {{
            set_effect(effect_name);
            Serial.print("EFFECT ");
            Serial.println(effect_name);
        }}
        return;
    }}

    // Speed: SPEED <0-255>
    if (strncmp(cmd, "SPEED", 5) == 0) {{
        int s;
        if (sscanf(cmd + 6, "%d", &s) == 1) {{
            speed = constrain(s, 1, 255);
            Serial.print("SPEED ");
            Serial.println(speed);
        }}
        return;
    }}

    // Color: COLOR <R> <G> <B>
    if (strncmp(cmd, "COLOR", 5) == 0) {{
        int r, g, b;
        if (sscanf(cmd + 6, "%d %d %d", &r, &g, &b) == 3) {{
            current_color = CRGB(r, g, b);
            Serial.print("COLOR ");
            Serial.print(r);
            Serial.print(",");
            Serial.print(g);
            Serial.print(",");
            Serial.println(b);
        }}
        return;
    }}

    Serial.println("CMD_OK");
}}

void set_effect(char* name) {{
    if (strcmp(name, "solid") == 0)      current_effect = EFFECT_SOLID;
    else if (strcmp(name, "rainbow") == 0) current_effect = EFFECT_RAINBOW;
    else if (strcmp(name, "pulse") == 0)  current_effect = EFFECT_PULSE;
    else if (strcmp(name, "fire") == 0)   current_effect = EFFECT_FIRE;
    else if (strcmp(name, "wave") == 0)   current_effect = EFFECT_WAVE;
    else if (strcmp(name, "running") == 0) current_effect = EFFECT_RUNNING;
    else if (strcmp(name, "random") == 0) current_effect = EFFECT_RANDOM;
    else if (strcmp(name, "chase") == 0)  current_effect = EFFECT_CHASE;
}}

void update_effect() {{
    uint32_t now = millis();
    if (now - last_update < (256 - speed)) return;
    last_update = now;

    switch (current_effect) {{
        case EFFECT_SOLID:
            fill_solid(leds, NUM_LEDS, current_color);
            break;

        case EFFECT_RAINBOW: {{
            uint8_t increment = speed;
            for (int i = 0; i < NUM_LEDS; i++) {{
                leds[i] = CHSV((i * 256 / NUM_LEDS + increment) % 256, 255, current_brightness);
            }}
            break;
        }}

        case EFFECT_PULSE: {{
            uint8_t wave = sin8(now / (32 / speed));
            fill_solid(leds, NUM_LEDS, current_color);
            for (int i = 0; i < NUM_LEDS; i++) {{
                leds[i].nscale8(wave);
            }}
            break;
        }}

        case EFFECT_WAVE: {{
            for (int i = 0; i < NUM_LEDS; i++) {{
                uint8_t wave = sin8((i * 8 + now / (16 / speed)) & 0xFF);
                leds[i] = CHSV(wave, 255, current_brightness);
            }}
            break;
        }}

        case EFFECT_RUNNING: {{
            fill_solid(leds, NUM_LEDS, CRGB::Black);
            int pos = (now / (32 / speed)) % NUM_LEDS;
            leds[pos] = current_color;
            break;
        }}

        case EFFECT_CHASE: {{
            fill_solid(leds, NUM_LEDS, CRGB::Black);
            int step = NUM_LEDS / 5;
            int offset = (now / (32 / speed)) % step;
            for (int i = 0; i < 5; i++) {{
                int pos = (offset + i * step) % NUM_LEDS;
                leds[pos] = current_color;
            }}
            break;
        }}

        case EFFECT_RANDOM: {{
            for (int i = 0; i < NUM_LEDS / 10; i++) {{
                int pos = random(NUM_LEDS);
                leds[pos] = CHSV(random(256), 200, current_brightness);
            }}
            break;
        }}

        case EFFECT_FIRE:
            // Simplified fire effect
            for (int i = 0; i < NUM_LEDS; i++) {{
                uint8_t heat = random(256);
                leds[i] = HeatColor(heat);
            }}
            break;
    }}
}}
"""


IR_REMOTE_TEMPLATE = """
/**
 * IR Remote Control Sketch
 * Generated by Arduino Vibe IDE
 */

#include <IRremote.h>

#define RECV_PIN {ir_pin}

IRrecv irrecv(RECV_PIN);
decode_results results;

// IR command buffer for serial communication
#define CMD_BUFFER_SIZE 64
char cmd_buffer[CMD_BUFFER_SIZE];
int cmd_idx = 0;

// Stored IR codes for replay
#define MAX_CODES 32
struct IRCode {{
    char name[32];
    uint64_t code;
    uint8_t protocol;
}} ir_codes[MAX_CODES];
int ir_code_count = 0;

void setup() {{
    Serial.begin(115200);
    while (!Serial) {{ }}

    irrecv.enableIRIn();
    Serial.println("IR_READY");
    Serial.println("IR receiver initialized");
}}

void loop() {{
    parse_serial_command();

    if (irrecv.decode(&results)) {{
        char msg[128];
        snprintf(msg, sizeof(msg), "IR_RECV:%s:0x%08lX",
                 protocol_name(results.value), results.value);
        Serial.println(msg);
        irrecv.resume();
    }}
}}

void parse_serial_command() {{
    while (Serial.available()) {{
        char c = Serial.read();
        if (c == '\\\\n') {{
            cmd_buffer[cmd_idx] = '\\\\0';
            process_command(cmd_buffer);
            cmd_idx = 0;
        }} else if (cmd_idx < CMD_BUFFER_SIZE - 1) {{
            cmd_buffer[cmd_idx++] = c;
        }}
    }}
}}

void process_command(char* cmd) {{
    // Send IR code: IR_SEND <name>
    if (strncmp(cmd, "IR_SEND", 7) == 0) {{
        char name[32];
        if (sscanf(cmd + 8, "%31s", name) == 1) {{
            send_ir_by_name(name);
        }}
        return;
    }}

    // Send raw code: IR_RAW <hex_code>
    if (strncmp(cmd, "IR_RAW", 6) == 0) {{
        unsigned long code;
        if (sscanf(cmd + 7, "%08lx", &code) == 1) {{
            irsend.sendNEC(code, 32);
            Serial.print("IR_RAW ");
            Serial.println(code);
        }}
        return;
    }}

    // Save code: IR_SAVE <name> <hex_code>
    if (strncmp(cmd, "IR_SAVE", 7) == 0) {{
        char name[32];
        unsigned long code;
        if (sscanf(cmd + 8, "%31s %08lx", name, &code) == 2) {{
            save_ir_code(name, code);
        }}
        return;
    }}

    // List codes
    if (strcmp(cmd, "IR_LIST") == 0) {{
        Serial.println("IR_CODES:");
        for (int i = 0; i < ir_code_count; i++) {{
            Serial.print("  ");
            Serial.print(ir_codes[i].name);
            Serial.print(":0x");
            Serial.println(ir_codes[i].code, HEX);
        }}
    }}

    Serial.println("CMD_OK");
}}

void send_ir_by_name(char* name) {{
    for (int i = 0; i < ir_code_count; i++) {{
        if (strcmp(ir_codes[i].name, name) == 0) {{
            irsend.sendNEC(ir_codes[i].code, 32);
            Serial.print("IR_SEND ");
            Serial.println(name);
            return;
        }}
    }}
    Serial.print("IR_NOT_FOUND:");
    Serial.println(name);
}}

void save_ir_code(char* name, uint64_t code) {{
    if (ir_code_count < MAX_CODES) {{
        strncpy(ir_codes[ir_code_count].name, name, 31);
        ir_codes[ir_code_count].code = code;
        ir_codes[ir_code_count].protocol = NEC;
        ir_code_count++;
        Serial.print("IR_SAVED:");
        Serial.println(name);
    }}
}}

const char* protocol_name(unsigned long code) {{
    // Simplified protocol detection
    return "NEC";
}}
"""


SENSOR_TEMPLATE = """
/**
 * Sensor Reading Sketch - {description}
 * Generated by Arduino Vibe IDE
 */

#include <Wire.h>

{includes}

// Pin Configuration
{pin_defs}

// Runtime command parser
#define CMD_BUFFER_SIZE 64
char cmd_buffer[CMD_BUFFER_SIZE];
int cmd_idx = 0;

void setup() {{
    Serial.begin(115200);
    while (!Serial) {{ }}

    Wire.begin();
    {setup_code}

    Serial.println("SENSOR_READY");
    Serial.println("Sensors initialized");
}}

void loop() {{
    parse_serial_command();
    read_sensors();
    delay(100);
}}

void parse_serial_command() {{
    while (Serial.available()) {{
        char c = Serial.read();
        if (c == '\\\\n') {{
            cmd_buffer[cmd_idx] = '\\\\0';
            process_command(cmd_buffer);
            cmd_idx = 0;
        }} else if (cmd_idx < CMD_BUFFER_SIZE - 1) {{
            cmd_buffer[cmd_idx++] = c;
        }}
    }}
}}

void process_command(char* cmd) {{
    // Read all sensors
    if (strcmp(cmd, "SENSOR_READ") == 0 || strcmp(cmd, "READ") == 0) {{
        read_sensors();
        return;
    }}

    // Set report interval
    if (strncmp(cmd, "INTERVAL", 8) == 0) {{
        int interval;
        if (sscanf(cmd + 9, "%d", &interval) == 1) {{
            Serial.print("INTERVAL ");
            Serial.println(interval);
        }}
        return;
    }}

    Serial.println("CMD_OK");
}}

void read_sensors() {{
{sensor_read_code}
}}
"""


SERVO_TEMPLATE = """
/**
 * Servo Control Sketch
 * Generated by Arduino Vibe IDE
 */

#include <Servo.h>

{servo_defs}

#define CMD_BUFFER_SIZE 64
char cmd_buffer[CMD_BUFFER_SIZE];
int cmd_idx = 0;

void setup() {{
    Serial.begin(115200);
    while (!Serial) {{ }}

{servo_setup}

    Serial.println("SERVO_READY");
    Serial.print("SERVO_COUNT=");
    Serial.println({servo_count});
}}

void loop() {{
    parse_serial_command();
}}

void parse_serial_command() {{
    while (Serial.available()) {{
        char c = Serial.read();
        if (c == '\\\\n') {{
            cmd_buffer[cmd_idx] = '\\\\0';
            process_command(cmd_buffer);
            cmd_idx = 0;
        }} else if (cmd_idx < CMD_BUFFER_SIZE - 1) {{
            cmd_buffer[cmd_idx++] = c;
        }}
    }}
}}

void process_command(char* cmd) {{
    // Move servo: SERVO <index> <angle>
    if (strncmp(cmd, "SERVO", 5) == 0) {{
        int idx, angle;
        if (sscanf(cmd + 6, "%d %d", &idx, &angle) == 2) {{
            move_servo(idx, constrain(angle, 0, 180));
            Serial.print("SERVO_");
            Serial.print(idx);
            Serial.print(":");
            Serial.println(angle);
        }}
        return;
    }}

    // All servos home: SERVO_HOME
    if (strcmp(cmd, "SERVO_HOME") == 0) {{
        for (int i = 0; i < {servo_count}; i++) {{
            move_servo(i, 90);
        }}
        Serial.println("SERVO_HOME OK");
        return;
    }}

    Serial.println("CMD_OK");
}}

void move_servo(int idx, int angle) {{
{servo_move_code}
}}
"""


BT_BRIDGE_TEMPLATE = """
/**
 * Bluetooth Serial Bridge Sketch
 * HC-05 Software Serial Bridge
 * Generated by Arduino Vibe IDE
 */

#include <SoftwareSerial.h>

// HC-05 Wiring: RXD -> D11, TXD -> D10
#define BT_RX_PIN 11
#define BT_TX_PIN 10
#define BT_BAUDRATE 9600

SoftwareSerial btSerial(BT_RX_PIN, BT_TX_PIN);

#define CMD_BUFFER_SIZE 128
char cmd_buffer[CMD_BUFFER_SIZE];
int cmd_idx = 0;

void setup() {{
    Serial.begin(115200);
    btSerial.begin(BT_BAUDRATE);

    Serial.println("BT_BRIDGE_READY");
    Serial.println("HC-05 bridge initialized");

    btSerial.println("BT_READY");
}}

void loop() {{
    // Forward Hardware Serial -> Bluetooth
    while (Serial.available()) {{
        char c = Serial.read();
        btSerial.write(c);
    }}

    // Forward Bluetooth -> Hardware Serial
    while (btSerial.available()) {{
        char c = btSerial.read();
        Serial.write(c);
    }}
}}
"""


GENERIC_TEMPLATE = """
/**
 * {description}
 * Generated by Arduino Vibe IDE
 */

{includes}

// Pin Configuration
{pin_defs}

// Runtime command parser for serial control
#define CMD_BUFFER_SIZE 64
char cmd_buffer[CMD_BUFFER_SIZE];
int cmd_idx = 0;

void setup() {{
    Serial.begin(115200);
    while (!Serial) {{ }}

{setup_code}

    Serial.println("READY");
    Serial.println("Arduino Vibe IDE sketch initialized");
}}

void loop() {{
    parse_serial_command();
{main_loop}
}}

void parse_serial_command() {{
    while (Serial.available()) {{
        char c = Serial.read();
        if (c == '\\\\n') {{
            cmd_buffer[cmd_idx] = '\\\\0';
            process_command(cmd_buffer);
            cmd_idx = 0;
        }} else if (cmd_idx < CMD_BUFFER_SIZE - 1) {{
            cmd_buffer[cmd_idx++] = c;
        }}
    }}
}}

void process_command(char* cmd) {{
{command_handlers}
    Serial.println("CMD_OK");
}}
"""


# ─── Prompt templates for AI ───────────────────────────────────────

SYSTEM_PROMPT = """
You are an expert Arduino C++ firmware engineer. Generate clean, well-structured
Arduino sketches based on natural language descriptions.

Requirements:
- Use modern C++ practices within Arduino constraints
- Include error handling where practical
- Add serial command parsing for runtime control
- Comment all major sections
- Use #define for pin mappings (easy to reconfigure)
- Return ONLY the .ino code, no markdown fences or explanations

Board context: {board}
Hardware context: {hardware_context}
"""


def build_led_prompt(
    description: str = "LED control",
    led_pin: int = 6,
    num_leds: int = 288,
    led_type: str = "SK6812",
    color_order: str = "GRBW",
    brightness: int = 128,
    board: str = "arduino:avr:nano",
) -> tuple[str, str]:
    """Build LED sketch generation prompt."""
    system = SYSTEM_PROMPT.format(
        board=board,
        hardware_context=(
            f"FastLED with {led_type} LEDs, {num_leds} count, "
            f"data pin {led_pin}, color order {color_order}"
        ),
    )

    user = f"""
Generate an Arduino sketch for: {description}

Hardware:
- Board: {board}
- LEDs: {led_type} ({num_leds} LEDs)
- Data Pin: D{led_pin}
- Color Order: {color_order}
- Default Brightness: {brightness}

Features:
- FastLED library integration
- Serial command interface for runtime control
  - LED <index> <R> <G> <B> - Set individual LED
  - ALL <R> <G> <B> - Set all LEDs
  - BRIGHT <0-255> - Set brightness
  - EFFECT <name> - Set animation effect
  - SPEED <0-255> - Set animation speed
  - COLOR <R> <G> <B> - Set base color for effects
- Animation effects: solid, rainbow, pulse, fire, wave, running, chase, random
- Non-blocking timing with millis()
"""

    return system, user


def build_ir_prompt(
    ir_pin: int = 2,
    board: str = "arduino:avr:nano",
) -> tuple[str, str]:
    """Build IR remote sketch prompt."""
    system = SYSTEM_PROMPT.format(
        board=board,
        hardware_context=(
            f"IR receiver on pin D{ir_pin}, IRremote library"
        ),
    )

    user = f"""
Generate an Arduino sketch for IR remote control and relay.

Hardware:
- Board: {board}
- IR Receiver Pin: D{ir_pin}
- Library: IRremote

Features:
- Receive IR signals and decode
- Serial command interface:
  - IR_SEND <name> - Send stored IR code
  - IR_RAW <hex_code> - Send raw NEC code
  - IR_SAVE <name> <hex_code> - Store IR code
  - IR_LIST - List stored codes
- Report received IR codes over serial
"""

    return system, user


def build_sensor_prompt(
    sensors: list[str] = None,
    board: str = "arduino:avr:nano",
) -> tuple[str, str]:
    """Build sensor reading sketch prompt."""
    sensor_list = sensors or ["DHT22 temperature/humidity"]

    system = SYSTEM_PROMPT.format(
        board=board,
        hardware_context=(
            f"Sensors: {', '.join(sensor_list)}"
        ),
    )

    user = f"""
Generate an Arduino sketch for reading sensor data.

Hardware:
- Board: {board}
- Sensors: {', '.join(sensor_list)}

Features:
- Read sensor values at regular intervals
- Serial output with structured format: SENSOR <type>:<value>
- Serial command interface:
  - SENSOR_READ or READ - Trigger immediate reading
  - INTERVAL <ms> - Set reading interval
"""

    return system, user


def build_servo_prompt(
    servos: list[dict] = None,
    board: str = "arduino:avr:nano",
) -> tuple[str, str]:
    """Build servo control sketch prompt."""
    default_servos = [{"pin": 9, "name": "servo1"}, {"pin": 10, "name": "servo2"}]
    servo_list = servos or default_servos

    pins_str = ", ".join(
        f"{s.get('name', 'servo')} on D{s.get('pin', '?')}" for s in servo_list
    )

    system = SYSTEM_PROMPT.format(
        board=board,
        hardware_context=f"Servos: {pins_str}",
    )

    user = f"""
Generate an Arduino sketch for servo motor control.

Hardware:
- Board: {board}
- Servos: {pins_str}

Features:
- Servo library integration
- Serial command interface:
  - SERVO <index> <angle> - Move servo to angle (0-180)
  - SERVO_HOME - Move all servos to center position
- Non-blocking control
"""

    return system, user


def build_generic_prompt(
    description: str,
    hardware: str = "",
    board: str = "arduino:avr:nano",
    features: str = "",
) -> tuple[str, str]:
    """Build generic sketch generation prompt."""
    system = SYSTEM_PROMPT.format(
        board=board,
        hardware_context=hardware or "Standard Arduino board",
    )

    user = f"""
Generate an Arduino sketch: {description}

Hardware:
- Board: {board}
- Configuration: {hardware}

Features:
{features}

Requirements:
- Include serial command parsing for runtime control
- Use non-blocking timing (millis())
- Well-commented code
- #define for pin mappings
- Return READY status on startup
"""

    return system, user


def build_bt_bridge_prompt(
    bt_rx: int = 11,
    bt_tx: int = 10,
    baudrate: int = 9600,
    board: str = "arduino:avr:nano",
) -> tuple[str, str]:
    """Build Bluetooth bridge sketch prompt."""
    system = SYSTEM_PROMPT.format(
        board=board,
        hardware_context=(
            f"HC-05 Bluetooth module, RXD->D{bt_rx}, TXD->D{bt_tx}, "
            f"baudrate {baudrate}, SoftwareSerial"
        ),
    )

    user = f"""
Generate an Arduino sketch for HC-05 Bluetooth serial bridge.

Hardware:
- Board: {board}
- HC-05 RXD -> D{bt_rx}
- HC-05 TXD -> D{bt_tx}
- Baudrate: {baudrate}
- Library: SoftwareSerial

Features:
- Full-duplex serial bridge between hardware Serial and Bluetooth
- Transparent data forwarding both directions
- Ready status reporting
"""

    return system, user


def generate_sketch_from_prompt(
    prompt: str,
    board: str = "arduino:avr:nano",
    hardware_context: dict = None,
) -> str:
    """
    Generate an Arduino sketch from a natural language prompt.
    Uses template-based generation (AI integration point).

    Args:
        prompt: Natural language description
        board: Target board FQBN
        hardware_context: Dict with hardware configuration

    Returns:
        Generated .ino sketch code
    """
    ctx = hardware_context or {}
    prompt_lower = prompt.lower()

    # Determine sketch type from prompt
    if any(kw in prompt_lower for kw in ["led", "neopixel", "ws2812", "sk6812", "fastled", "rgb"]):
        return LED_SKETCH_TEMPLATE.format(
            description=prompt,
            led_pin=ctx.get("led_pin", 6),
            num_leds=ctx.get("num_leds", 288),
            led_type=ctx.get("led_type", "SK6812"),
            color_order=ctx.get("color_order", "GRBW"),
            brightness=ctx.get("brightness", 128),
        )

    if any(kw in prompt_lower for kw in ["ir", "remote", "infrared", "irremote"]):
        return IR_REMOTE_TEMPLATE.format(ir_pin=ctx.get("ir_pin", 2))

    if any(kw in prompt_lower for kw in ["sensor", "dht", "bmp", "bme", "temperature", "humidity", "pressure"]):
        sensor_desc = prompt
        includes = "#include <DHT.h>\n#include <DHT_U.h>"
        pin_defs = "#define DHT_PIN 4\n#define DHT_TYPE DHT22"
        setup_code = "DHT dht(DHT_PIN, DHT_TYPE);\ndht.begin();"
        read_code = """
    float temp = dht.readTemperature();
    float hum = dht.readHumidity();
    if (!isnan(temp) && !isnan(hum)) {
        Serial.print("SENSOR_TEMP:");
        Serial.println(temp, 2);
        Serial.print("SENSOR_HUM:");
        Serial.println(hum, 2);
    }
"""
        return SENSOR_TEMPLATE.format(
            description=sensor_desc,
            includes=includes,
            pin_defs=pin_defs,
            setup_code=setup_code,
            sensor_read_code=read_code,
        )

    if any(kw in prompt_lower for kw in ["servo", "motor", "rotate"]):
        servo_count = ctx.get("servo_count", 1)
        servo_defs = "#include <Servo.h>\nServo servo1;"
        servo_setup = "servo1.attach(" + str(ctx.get("servo_pin", 9)) + ");"
        servo_move = "    if (idx == 0) servo1.write(angle);"
        return SERVO_TEMPLATE.format(
            servo_defs=servo_defs,
            servo_setup=servo_setup,
            servo_count=servo_count,
            servo_move_code=servo_move,
        )

    if any(kw in prompt_lower for kw in ["bluetooth", "bt", "hc-05", "hc05", "rfcomm"]):
        return BT_BRIDGE_TEMPLATE

    # Generic template
    return GENERIC_TEMPLATE.format(
        description=prompt,
        includes="// Add library includes here",
        pin_defs="// Define pins here",
        setup_code="// Initialize hardware here",
        main_loop="// Main loop logic here\ndelay(100);",
        command_handlers="// Add command handlers here",
    )


# ─── LED color helpers ─────────────────────────────────────────────

LED_PRESET_COLORS = {
    "white": (255, 255, 255),
    "red": (255, 0, 0),
    "green": (0, 255, 0),
    "blue": (0, 0, 255),
    "yellow": (255, 255, 0),
    "cyan": (0, 255, 255),
    "magenta": (255, 0, 255),
    "orange": (255, 165, 0),
    "purple": (128, 0, 128),
    "pink": (255, 192, 203),
    "off": (0, 0, 0),
}


def build_led_command(
    command: str,
    led_index: int = -1,
    red: int = 255,
    green: int = 255,
    blue: int = 255,
    brightness: int = -1,
    effect: str = "",
    speed: int = -1,
) -> str:
    """
    Build an LED control command string.

    Args:
        command: LED | ALL | BRIGHT | EFFECT | SPEED | COLOR
        led_index: LED index (for individual LED control)
        red, green, blue: RGB values (0-255)
        brightness: Brightness (0-255)
        effect: Effect name
        speed: Animation speed (1-255)

    Returns:
        Command string ready to send over serial
    """
    if command.upper() == "LED" and led_index >= 0:
        return f"LED {led_index} {red} {green} {blue}"
    elif command.upper() == "ALL":
        return f"ALL {red} {green} {blue}"
    elif command.upper() == "BRIGHT" and brightness >= 0:
        return f"BRIGHT {brightness}"
    elif command.upper() == "EFFECT" and effect:
        return f"EFFECT {effect}"
    elif command.upper() == "SPEED" and speed >= 0:
        return f"SPEED {speed}"
    elif command.upper() == "COLOR":
        return f"COLOR {red} {green} {blue}"
    return ""


if __name__ == "__main__":
    # Test sketch generation
    sketch = generate_sketch_from_prompt(
        "LED controller with FastLED and SK6812",
        hardware_context={
            "led_pin": 6,
            "num_leds": 288,
            "led_type": "SK6812",
        },
    )
    print(sketch[:500])
